# Generated by Django 4.1.7 on 2023-04-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_alter_subcategories_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategories",
            name="subcat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.categories",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subcategories",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
