# Generated by Django 4.1.7 on 2023-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_size_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="L",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="M",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="S",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
