# Generated by Django 4.1.7 on 2023-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_remove_product_sizes_product_l_product_m_product_s"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
