# Generated by Django 4.1.7 on 2023-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_product_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField(default="")),
                ("password", models.CharField(max_length=50)),
                ("confirmpassword", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
